spring:
  datasource:
    url: jdbc:mariadb://db:3306/coumap
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  mvc:
    servlet:
      path: /api/v1

server:
  port: 8080